package com.tz.mapper;

import com.tz.pojo.SearchRecords;
import com.tz.pojo.SearchRecordsExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface SearchRecordsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_records
     *
     * @mbg.generated Sun Dec 06 14:06:29 CST 2020
     */
    long countByExample(SearchRecordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_records
     *
     * @mbg.generated Sun Dec 06 14:06:29 CST 2020
     */
    int deleteByExample(SearchRecordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_records
     *
     * @mbg.generated Sun Dec 06 14:06:29 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_records
     *
     * @mbg.generated Sun Dec 06 14:06:29 CST 2020
     */
    int insert(SearchRecords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_records
     *
     * @mbg.generated Sun Dec 06 14:06:29 CST 2020
     */
    int insertSelective(SearchRecords record);


    /**
     * 查询所有记录
     * @return
     */
    List<String> getAllRecords();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_records
     *
     * @mbg.generated Sun Dec 06 14:06:29 CST 2020
     */

    List<SearchRecords> selectByExample(SearchRecordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_records
     *
     * @mbg.generated Sun Dec 06 14:06:29 CST 2020
     */
    SearchRecords selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_records
     *
     * @mbg.generated Sun Dec 06 14:06:29 CST 2020
     */
    int updateByExampleSelective(@Param("record") SearchRecords record, @Param("example") SearchRecordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_records
     *
     * @mbg.generated Sun Dec 06 14:06:29 CST 2020
     */
    int updateByExample(@Param("record") SearchRecords record, @Param("example") SearchRecordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_records
     *
     * @mbg.generated Sun Dec 06 14:06:29 CST 2020
     */
    int updateByPrimaryKeySelective(SearchRecords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_records
     *
     * @mbg.generated Sun Dec 06 14:06:29 CST 2020
     */
    int updateByPrimaryKey(SearchRecords record);
}