package com.tz.mapper;

import com.tz.pojo.UsersLikeVideos;
import com.tz.pojo.UsersLikeVideosExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface UsersLikeVideosMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_like_videos
     *
     * @mbg.generated Sun Dec 06 14:06:29 CST 2020
     */
    long countByExample(UsersLikeVideosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_like_videos
     *
     * @mbg.generated Sun Dec 06 14:06:29 CST 2020
     */
    int deleteByExample(UsersLikeVideosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_like_videos
     *
     * @mbg.generated Sun Dec 06 14:06:29 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_like_videos
     *
     * @mbg.generated Sun Dec 06 14:06:29 CST 2020
     */
    int insert(UsersLikeVideos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_like_videos
     *
     * @mbg.generated Sun Dec 06 14:06:29 CST 2020
     */
    int insertSelective(UsersLikeVideos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_like_videos
     *
     * @mbg.generated Sun Dec 06 14:06:29 CST 2020
     */
    List<UsersLikeVideos> selectByExample(UsersLikeVideosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_like_videos
     *
     * @mbg.generated Sun Dec 06 14:06:29 CST 2020
     */
    UsersLikeVideos selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_like_videos
     *
     * @mbg.generated Sun Dec 06 14:06:29 CST 2020
     */
    int updateByExampleSelective(@Param("record") UsersLikeVideos record, @Param("example") UsersLikeVideosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_like_videos
     *
     * @mbg.generated Sun Dec 06 14:06:29 CST 2020
     */
    int updateByExample(@Param("record") UsersLikeVideos record, @Param("example") UsersLikeVideosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_like_videos
     *
     * @mbg.generated Sun Dec 06 14:06:29 CST 2020
     */
    int updateByPrimaryKeySelective(UsersLikeVideos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_like_videos
     *
     * @mbg.generated Sun Dec 06 14:06:29 CST 2020
     */
    int updateByPrimaryKey(UsersLikeVideos record);
}