package com.tz.pojo;

import java.util.Date;

public class Comments {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.id
     *
     * @mbg.generated Thu Jan 21 19:47:37 CST 2021
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.father_comment_id
     *
     * @mbg.generated Thu Jan 21 19:47:37 CST 2021
     */
    private String fatherCommentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.to_user_id
     *
     * @mbg.generated Thu Jan 21 19:47:37 CST 2021
     */
    private String toUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.video_id
     *
     * @mbg.generated Thu Jan 21 19:47:37 CST 2021
     */
    private String videoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.from_user_id
     *
     * @mbg.generated Thu Jan 21 19:47:37 CST 2021
     */
    private String fromUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.create_time
     *
     * @mbg.generated Thu Jan 21 19:47:37 CST 2021
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.comment
     *
     * @mbg.generated Thu Jan 21 19:47:37 CST 2021
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.id
     *
     * @return the value of comments.id
     *
     * @mbg.generated Thu Jan 21 19:47:37 CST 2021
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.id
     *
     * @param id the value for comments.id
     *
     * @mbg.generated Thu Jan 21 19:47:37 CST 2021
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.father_comment_id
     *
     * @return the value of comments.father_comment_id
     *
     * @mbg.generated Thu Jan 21 19:47:37 CST 2021
     */
    public String getFatherCommentId() {
        return fatherCommentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.father_comment_id
     *
     * @param fatherCommentId the value for comments.father_comment_id
     *
     * @mbg.generated Thu Jan 21 19:47:37 CST 2021
     */
    public void setFatherCommentId(String fatherCommentId) {
        this.fatherCommentId = fatherCommentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.to_user_id
     *
     * @return the value of comments.to_user_id
     *
     * @mbg.generated Thu Jan 21 19:47:37 CST 2021
     */
    public String getToUserId() {
        return toUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.to_user_id
     *
     * @param toUserId the value for comments.to_user_id
     *
     * @mbg.generated Thu Jan 21 19:47:37 CST 2021
     */
    public void setToUserId(String toUserId) {
        this.toUserId = toUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.video_id
     *
     * @return the value of comments.video_id
     *
     * @mbg.generated Thu Jan 21 19:47:37 CST 2021
     */
    public String getVideoId() {
        return videoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.video_id
     *
     * @param videoId the value for comments.video_id
     *
     * @mbg.generated Thu Jan 21 19:47:37 CST 2021
     */
    public void setVideoId(String videoId) {
        this.videoId = videoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.from_user_id
     *
     * @return the value of comments.from_user_id
     *
     * @mbg.generated Thu Jan 21 19:47:37 CST 2021
     */
    public String getFromUserId() {
        return fromUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.from_user_id
     *
     * @param fromUserId the value for comments.from_user_id
     *
     * @mbg.generated Thu Jan 21 19:47:37 CST 2021
     */
    public void setFromUserId(String fromUserId) {
        this.fromUserId = fromUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.create_time
     *
     * @return the value of comments.create_time
     *
     * @mbg.generated Thu Jan 21 19:47:37 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.create_time
     *
     * @param createTime the value for comments.create_time
     *
     * @mbg.generated Thu Jan 21 19:47:37 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.comment
     *
     * @return the value of comments.comment
     *
     * @mbg.generated Thu Jan 21 19:47:37 CST 2021
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.comment
     *
     * @param comment the value for comments.comment
     *
     * @mbg.generated Thu Jan 21 19:47:37 CST 2021
     */
    public void setComment(String comment) {
        this.comment = comment;
    }
}