package com.tz.pojo;

import java.util.Date;

public class UsersReport {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_report.id
     *
     * @mbg.generated Sun Dec 06 14:06:29 CST 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_report.deal_user_id
     *
     * @mbg.generated Sun Dec 06 14:06:29 CST 2020
     */
    private String dealUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_report.deal_video_id
     *
     * @mbg.generated Sun Dec 06 14:06:29 CST 2020
     */
    private String dealVideoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_report.title
     *
     * @mbg.generated Sun Dec 06 14:06:29 CST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_report.content
     *
     * @mbg.generated Sun Dec 06 14:06:29 CST 2020
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_report.userid
     *
     * @mbg.generated Sun Dec 06 14:06:29 CST 2020
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_report.create_time
     *
     * @mbg.generated Sun Dec 06 14:06:29 CST 2020
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_report.id
     *
     * @return the value of users_report.id
     *
     * @mbg.generated Sun Dec 06 14:06:29 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_report.id
     *
     * @param id the value for users_report.id
     *
     * @mbg.generated Sun Dec 06 14:06:29 CST 2020
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_report.deal_user_id
     *
     * @return the value of users_report.deal_user_id
     *
     * @mbg.generated Sun Dec 06 14:06:29 CST 2020
     */
    public String getDealUserId() {
        return dealUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_report.deal_user_id
     *
     * @param dealUserId the value for users_report.deal_user_id
     *
     * @mbg.generated Sun Dec 06 14:06:29 CST 2020
     */
    public void setDealUserId(String dealUserId) {
        this.dealUserId = dealUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_report.deal_video_id
     *
     * @return the value of users_report.deal_video_id
     *
     * @mbg.generated Sun Dec 06 14:06:29 CST 2020
     */
    public String getDealVideoId() {
        return dealVideoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_report.deal_video_id
     *
     * @param dealVideoId the value for users_report.deal_video_id
     *
     * @mbg.generated Sun Dec 06 14:06:29 CST 2020
     */
    public void setDealVideoId(String dealVideoId) {
        this.dealVideoId = dealVideoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_report.title
     *
     * @return the value of users_report.title
     *
     * @mbg.generated Sun Dec 06 14:06:29 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_report.title
     *
     * @param title the value for users_report.title
     *
     * @mbg.generated Sun Dec 06 14:06:29 CST 2020
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_report.content
     *
     * @return the value of users_report.content
     *
     * @mbg.generated Sun Dec 06 14:06:29 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_report.content
     *
     * @param content the value for users_report.content
     *
     * @mbg.generated Sun Dec 06 14:06:29 CST 2020
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_report.userid
     *
     * @return the value of users_report.userid
     *
     * @mbg.generated Sun Dec 06 14:06:29 CST 2020
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_report.userid
     *
     * @param userid the value for users_report.userid
     *
     * @mbg.generated Sun Dec 06 14:06:29 CST 2020
     */
    public void setUserid(String userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_report.create_time
     *
     * @return the value of users_report.create_time
     *
     * @mbg.generated Sun Dec 06 14:06:29 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_report.create_time
     *
     * @param createTime the value for users_report.create_time
     *
     * @mbg.generated Sun Dec 06 14:06:29 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}